import Head from "next/head";
import { Hero, Heading } from "../components/styles/GlobalStyles";

export default function About() {
  return (
    <>
      <Head>
        <title>NXT AI | About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero>
        <Heading>ABOUT</Heading>
      </Hero>
    </>
  );
}
