import Head from "next/head";
import { Hero, Heading } from "../components/styles/GlobalStyles";

export default function Home() {
  return (
    <>
      <Head>
        <title>NXT AI | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero>
        <Heading>NXT AI</Heading>
        <p><a href="/auth">Login</a></p>
      </Hero>
    </>
  );
}
