import Head from "next/head";
import { auth } from "../firebase/firebase";
import { useAuthState } from "react-firebase-hooks/auth";
import Hero from "../components/Hero";
import AddTask from "../components/AddTask";

export default function Home() {
  const [user] = useAuthState(auth);

  return (
    <div>
      <Head>
        <title>{user ? "firenote" : "firenote | Home"}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {user ? <AddTask /> : <Hero />}
    </div>
  );
}
